# Generated by Django 2.2.8 on 2021-11-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20211122_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritelist',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AddConstraint(
            model_name='favoritelist',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_favorite_list'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_shopping_list'),
        ),
    ]
