# Generated by Django 2.2.8 on 2021-11-02 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20211102_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Enter color HEX-code', regex='^#[\\da-fA-F]{6}$')], verbose_name='Цвет'),
        ),
    ]
